# Copyright (c) 2022-2025, The Isaac Lab Project Developers.
# All rights reserved.
# Original code is licensed under BSD-3-Clause.
#
# Copyright (c) 2025-2026, The Legged Lab Project Developers.
# All rights reserved.
# Modifications are licensed under BSD-3-Clause.
#
# This file contains code derived from Isaac Lab Project (BSD-3-Clause license)
# with modifications by Legged Lab Project (BSD-3-Clause license).


from legged_lab.envs.base.base_env import BaseEnv
from legged_lab.envs.base.base_env_config import BaseAgentCfg, BaseEnvCfg
from legged_lab.envs.g1.g1_config import (
    G1FlatAgentCfg,
    G1FlatEnvCfg,
    G1GravelAgentCfg,
    G1GravelEnvCfg,
    G1RoughAgentCfg,
    G1RoughEnvCfg,
)
from legged_lab.envs.gr2.gr2_config import (
    GR2FlatAgentCfg,
    GR2FlatEnvCfg,
    GR2RoughAgentCfg,
    GR2RoughEnvCfg,
)
from legged_lab.envs.h1.h1_config import (
    H1FlatAgentCfg,
    H1FlatEnvCfg,
    H1RoughAgentCfg,
    H1RoughEnvCfg,
)
from legged_lab.envs.magicbot_z1.z1_config import (
    MagicBotZ1FlatAgentCfg,
    MagicBotZ1FlatEnvCfg,
    MagicBotZ1FlatSprintAMPAgentCfg,
    MagicBotZ1FlatSprintAMPEnvCfg,
    MagicBotZ1FlatSprintAMPStage1AAgentCfg,
    MagicBotZ1FlatSprintAMPStage1AEnvCfg,
    MagicBotZ1FlatSprintAMPStage1BAgentCfg,
    MagicBotZ1FlatSprintAMPStage1BEnvCfg,
    MagicBotZ1FlatSprintAMPStage1CAgentCfg,
    MagicBotZ1FlatSprintAMPStage1CEnvCfg,
    MagicBotZ1FlatSprintAMPStage2AAgentCfg,
    MagicBotZ1FlatSprintAMPStage2AEnvCfg,
    MagicBotZ1FlatSprintAMPStage2BAgentCfg,
    MagicBotZ1FlatSprintAMPStage2BEnvCfg,
    MagicBotZ1FlatSprintAMPStage2CForwardAgentCfg,
    MagicBotZ1FlatSprintAMPStage2CForwardEnvCfg,
    MagicBotZ1FlatSprintAMPStage2DHighRefAgentCfg,
    MagicBotZ1FlatSprintAMPStage2DHighRefEnvCfg,
    MagicBotZ1FlatSprintAMPStage2EProgressAgentCfg,
    MagicBotZ1FlatSprintAMPStage2EProgressEnvCfg,
    MagicBotZ1FlatSprintAMPStage2FPostureAgentCfg,
    MagicBotZ1FlatSprintAMPStage2FPostureEnvCfg,
    MagicBotZ1FlatSprintAMPStage2GHoldAgentCfg,
    MagicBotZ1FlatSprintAMPStage2GHoldEnvCfg,
    MagicBotZ1FlatSprintAMPStage2HSpeedExtendAgentCfg,
    MagicBotZ1FlatSprintAMPStage2HSpeedExtendEnvCfg,
    MagicBotZ1FlatSprintAMPStage2IHighTrackAgentCfg,
    MagicBotZ1FlatSprintAMPStage2IHighTrackEnvCfg,
    MagicBotZ1FlatSprintAMPStage2JTurnRobustAgentCfg,
    MagicBotZ1FlatSprintAMPStage2JTurnRobustEnvCfg,
    MagicBotZ1FlatSprintAMPStage2KMixedRetentionAgentCfg,
    MagicBotZ1FlatSprintAMPStage2KMixedRetentionEnvCfg,
    MagicBotZ1FlatSprintAMPStage2LStabilityAnchorAgentCfg,
    MagicBotZ1FlatSprintAMPStage2LStabilityAnchorEnvCfg,
    MagicBotZ1FlatSprintAMPStage2MHeadGuardAgentCfg,
    MagicBotZ1FlatSprintAMPStage2MHeadGuardEnvCfg,
    MagicBotZ1FlatSprintAMPStage2NAgilityMixAgentCfg,
    MagicBotZ1FlatSprintAMPStage2NAgilityMixEnvCfg,
    MagicBotZ1FlatSprintAMPStage2OBalancedAgilityAgentCfg,
    MagicBotZ1FlatSprintAMPStage2OBalancedAgilityEnvCfg,
    MagicBotZ1FlatSprintAMPStage2PMixedCommandAgentCfg,
    MagicBotZ1FlatSprintAMPStage2PMixedCommandEnvCfg,
    MagicBotZ1FlatSprintAMPStage2QYawFocusAgentCfg,
    MagicBotZ1FlatSprintAMPStage2QYawFocusEnvCfg,
    MagicBotZ1FlatSprintAMPStage2RYawAuthorityAgentCfg,
    MagicBotZ1FlatSprintAMPStage2RYawAuthorityEnvCfg,
    MagicBotZ1FlatSprintAMPStage2SGatedPriorAgentCfg,
    MagicBotZ1FlatSprintAMPStage2SGatedPriorEnvCfg,
    MagicBotZ1FlatSprintAMPStage2TAgilityAuthorityAgentCfg,
    MagicBotZ1FlatSprintAMPStage2TAgilityAuthorityEnvCfg,
    MagicBotZ1FlatSprintAMPStage2UYawSpecialistAgentCfg,
    MagicBotZ1FlatSprintAMPStage2UYawSpecialistEnvCfg,
    MagicBotZ1FlatSprintAMPStage2VYawTransferAgentCfg,
    MagicBotZ1FlatSprintAMPStage2VYawTransferEnvCfg,
    MagicBotZ1FlatSprintAMPStage2WCommandConditionedAgentCfg,
    MagicBotZ1FlatSprintAMPStage2WCommandConditionedEnvCfg,
    MagicBotZ1FlatSprintAMPStage2XLowSpeedRobustAgentCfg,
    MagicBotZ1FlatSprintAMPStage2XLowSpeedRobustEnvCfg,
    MagicBotZ1FlatSprintAMPStage2YBaselineBridgeAgentCfg,
    MagicBotZ1FlatSprintAMPStage2YBaselineBridgeEnvCfg,
    MagicBotZ1FlatSprintAMPStage2ZHighStartAgentCfg,
    MagicBotZ1FlatSprintAMPStage2ZHighStartEnvCfg,
    MagicBotZ1FlatSprintAMPStage2AAStage1CExtendAgentCfg,
    MagicBotZ1FlatSprintAMPStage2AAStage1CExtendEnvCfg,
    MagicBotZ1FlatSprintAMPStage2ABHighTransitionAgentCfg,
    MagicBotZ1FlatSprintAMPStage2ABHighTransitionEnvCfg,
    MagicBotZ1FlatSprintBridgeAgentCfg,
    MagicBotZ1FlatSprintBridgeEnvCfg,
    MagicBotZ1RoughAgentCfg,
    MagicBotZ1RoughEnvCfg,
)
from legged_lab.utils.task_registry import task_registry

task_registry.register("h1_flat", BaseEnv, H1FlatEnvCfg(), H1FlatAgentCfg())
task_registry.register("h1_rough", BaseEnv, H1RoughEnvCfg(), H1RoughAgentCfg())
task_registry.register("g1_flat", BaseEnv, G1FlatEnvCfg(), G1FlatAgentCfg())
task_registry.register("g1_gravel", BaseEnv, G1GravelEnvCfg(), G1GravelAgentCfg())
task_registry.register("g1_rough", BaseEnv, G1RoughEnvCfg(), G1RoughAgentCfg())
task_registry.register("gr2_flat", BaseEnv, GR2FlatEnvCfg(), GR2FlatAgentCfg())
task_registry.register("gr2_rough", BaseEnv, GR2RoughEnvCfg(), GR2RoughAgentCfg())
task_registry.register("magicbot_z1_flat", BaseEnv, MagicBotZ1FlatEnvCfg(), MagicBotZ1FlatAgentCfg())
task_registry.register(
    "magicbot_z1_flat_sprint_bridge",
    BaseEnv,
    MagicBotZ1FlatSprintBridgeEnvCfg(),
    MagicBotZ1FlatSprintBridgeAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp",
    BaseEnv,
    MagicBotZ1FlatSprintAMPEnvCfg(),
    MagicBotZ1FlatSprintAMPAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage1a",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage1AEnvCfg(),
    MagicBotZ1FlatSprintAMPStage1AAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage1b",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage1BEnvCfg(),
    MagicBotZ1FlatSprintAMPStage1BAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage1c",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage1CEnvCfg(),
    MagicBotZ1FlatSprintAMPStage1CAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage2a",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage2AEnvCfg(),
    MagicBotZ1FlatSprintAMPStage2AAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage2b",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage2BEnvCfg(),
    MagicBotZ1FlatSprintAMPStage2BAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage2c_forward",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage2CForwardEnvCfg(),
    MagicBotZ1FlatSprintAMPStage2CForwardAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage2d_highref",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage2DHighRefEnvCfg(),
    MagicBotZ1FlatSprintAMPStage2DHighRefAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage2e_progress",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage2EProgressEnvCfg(),
    MagicBotZ1FlatSprintAMPStage2EProgressAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage2f_posture",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage2FPostureEnvCfg(),
    MagicBotZ1FlatSprintAMPStage2FPostureAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage2g_hold",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage2GHoldEnvCfg(),
    MagicBotZ1FlatSprintAMPStage2GHoldAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage2h_speedextend",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage2HSpeedExtendEnvCfg(),
    MagicBotZ1FlatSprintAMPStage2HSpeedExtendAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage2i_hightrack",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage2IHighTrackEnvCfg(),
    MagicBotZ1FlatSprintAMPStage2IHighTrackAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage2j_turnrobust",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage2JTurnRobustEnvCfg(),
    MagicBotZ1FlatSprintAMPStage2JTurnRobustAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage2k_mixedretention",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage2KMixedRetentionEnvCfg(),
    MagicBotZ1FlatSprintAMPStage2KMixedRetentionAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage2l_stabilityanchor",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage2LStabilityAnchorEnvCfg(),
    MagicBotZ1FlatSprintAMPStage2LStabilityAnchorAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage2m_headguard",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage2MHeadGuardEnvCfg(),
    MagicBotZ1FlatSprintAMPStage2MHeadGuardAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage2n_agilitymix",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage2NAgilityMixEnvCfg(),
    MagicBotZ1FlatSprintAMPStage2NAgilityMixAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage2o_balancedagility",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage2OBalancedAgilityEnvCfg(),
    MagicBotZ1FlatSprintAMPStage2OBalancedAgilityAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage2p_mixedcommand",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage2PMixedCommandEnvCfg(),
    MagicBotZ1FlatSprintAMPStage2PMixedCommandAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage2q_yawfocus",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage2QYawFocusEnvCfg(),
    MagicBotZ1FlatSprintAMPStage2QYawFocusAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage2r_yawauthority",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage2RYawAuthorityEnvCfg(),
    MagicBotZ1FlatSprintAMPStage2RYawAuthorityAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage2s_gatedprior",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage2SGatedPriorEnvCfg(),
    MagicBotZ1FlatSprintAMPStage2SGatedPriorAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage2t_agilityauthority",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage2TAgilityAuthorityEnvCfg(),
    MagicBotZ1FlatSprintAMPStage2TAgilityAuthorityAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage2u_yawspecialist",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage2UYawSpecialistEnvCfg(),
    MagicBotZ1FlatSprintAMPStage2UYawSpecialistAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage2v_yawtransfer",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage2VYawTransferEnvCfg(),
    MagicBotZ1FlatSprintAMPStage2VYawTransferAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage2w_cmdcond",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage2WCommandConditionedEnvCfg(),
    MagicBotZ1FlatSprintAMPStage2WCommandConditionedAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage2x_lowspeedrobust",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage2XLowSpeedRobustEnvCfg(),
    MagicBotZ1FlatSprintAMPStage2XLowSpeedRobustAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage2y_baselinebridge",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage2YBaselineBridgeEnvCfg(),
    MagicBotZ1FlatSprintAMPStage2YBaselineBridgeAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage2z_highstart",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage2ZHighStartEnvCfg(),
    MagicBotZ1FlatSprintAMPStage2ZHighStartAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage2aa_stage1c_extend",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage2AAStage1CExtendEnvCfg(),
    MagicBotZ1FlatSprintAMPStage2AAStage1CExtendAgentCfg(),
)
task_registry.register(
    "magicbot_z1_flat_sprint_amp_stage2ab_hightransition",
    BaseEnv,
    MagicBotZ1FlatSprintAMPStage2ABHighTransitionEnvCfg(),
    MagicBotZ1FlatSprintAMPStage2ABHighTransitionAgentCfg(),
)
task_registry.register("magicbot_z1_rough", BaseEnv, MagicBotZ1RoughEnvCfg(), MagicBotZ1RoughAgentCfg())
